aws_dbt_project:
  outputs:
    dev:
      account: YHGIBAS-ZJ87413
      database: AIRBNB
      password: *************
      role: ACCOUNTADMIN
      schema: DBT_SCHEMA
      threads: 1
      type: snowflake
      user: ************
      warehouse: COMPUTE_WH
  target: dev
